---

dev_env:
  # git tools
  - git
  - git-delta
  - github-cli

  # cli tools
  - bat
  - btop
  - curl
  - fastfetch
  - fd
  - fzf
  - openssh
  - ripgrep
  - zoxide

  # arch specific
  - reflector

  # shell & promp
  - fish
  - nushell
  - starship

  # tui
  - helix
  - lazygit
  - yazi
  - zellij

lang_tools:
  - docker
  - docker-compose

  - juliaup

  - python
  - python-pip
  - uv
